service: resetSession
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs15.x
  lambdaHashingVersion: 20201221

functions:
  resetSession:
    handler: index.handler
    memorySize: 128
    timeout: 180
    vpc:
      securityGroupIds:
        - sg-03f5b485d7cb35d38
      subnetIds:
        - subnet-0a951cac6805bd176
        - subnet-001de5ecd3df6ae3d
    package:
      exclude:
        - '**/**'
      include:
        - ./**
    description: Reset session
    events:
      - http:
          path: /resetSession
          method: POST
          private: true
