service: resetSession
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: 'us-east-2'
  stage: ${opt:stage, 'development'}
  environment:
      STAGE: ${opt:stage, 'development'}
      KEYNATBRDEV: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6ImY3ODM2NGJlLTc5Y2UtNDA2MS05OWZkLWNmMDExN2RmYTA2OCIsInVzZXIiOnsiZW1haWwiOiJwZWRyby52aXZhbGRpQHdhdnkuZ2xvYmFsIiwic3ViIjoiMjg4NzE4OTItYjAxMS00ODJjLWJhNjgtODRmOGVlOTM5YTlhIiwiZ3JvdXBJZHMiOlsiOGZhMGU3MGMtZTcwMC00MTcwLWFhZDQtMGMxZDFmOTQ1OTAzIiwiZjc4MzY0YmUtNzljZS00MDYxLTk5ZmQtY2YwMTE3ZGZhMDY4Il0sInJvbGVzIjpbIm9yZ2FuaXphdGlvbi5hZG1pbiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sImNyZWF0ZWRBdCI6MTU5ODk5MzI3ODY0NywiaWF0IjoxNTk4OTkzMjc4fQ.QF7MdwA6wrky8t6QvqUqQBkZtbaBsuoWgVZSfDVLffc'
      KEYNATHSPDEV: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6ImY3ODM2NGJlLTc5Y2UtNDA2MS05OWZkLWNmMDExN2RmYTA2OCIsInVzZXIiOnsiZW1haWwiOiJwZWRyby52aXZhbGRpQHdhdnkuZ2xvYmFsIiwic3ViIjoiMjg4NzE4OTItYjAxMS00ODJjLWJhNjgtODRmOGVlOTM5YTlhIiwiZ3JvdXBJZHMiOlsiOGZhMGU3MGMtZTcwMC00MTcwLWFhZDQtMGMxZDFmOTQ1OTAzIiwiZjc4MzY0YmUtNzljZS00MDYxLTk5ZmQtY2YwMTE3ZGZhMDY4Il0sInJvbGVzIjpbIm9yZ2FuaXphdGlvbi5hZG1pbiIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sImNyZWF0ZWRBdCI6MTU5ODk5MzI3ODY0NywiaWF0IjoxNTk4OTkzMjc4fQ.QF7MdwA6wrky8t6QvqUqQBkZtbaBsuoWgVZSfDVLffc'
      KEYAVONDEV: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbml6YXRpb25JZCI6IjMxNTVmZDZiLTU1MmItNDkyMy1iZjU2LWY3YWZlODlmMzFiZSIsInVzZXIiOnsiZW1haWwiOiJsdWNhcy5taXRyaUB3YXZ5Lmdsb2JhbCIsInN1YiI6IjA2NzNlYTVlLTIxMWMtNGNmYy1iOThlLTE5ZWQwMmQzOWMyYyIsImdyb3VwSWRzIjpbIjhmYTBlNzBjLWU3MDAtNDE3MC1hYWQ0LTBjMWQxZjk0NTkwMyIsIjMxNTVmZDZiLTU1MmItNDkyMy1iZjU2LWY3YWZlODlmMzFiZSIsImRmZWJmMGNjLTg1OTgtNDI5ZC04NTkzLTEyNjMzNDdjZjQzYSIsIjkxZTI5NDU3LTgyNzgtNDI0Yy05NWRjLWY2ZWMyZjM5OTE2YSIsIjEzMWZkMGUzLTNhNDItNDRmYS04ZTdiLTNiNGI4MzE5NjI1OCIsIjdlMmM4YWNjLWI5Y2MtNDUyNy04MmExLWMzODZhMmExNmJkNyIsImY3ODM2NGJlLTc5Y2UtNDA2MS05OWZkLWNmMDExN2RmYTA2OCIsIjZlODFmYmM0LWNlZjgtNGU1OC04N2QyLTA2M2VjZDQyMDljZSIsImVjYWI4ZmUxLTdjMTYtNGRlZS1hMjE2LTI2YTc2NDVmOWNhMiIsIjJjNjFiYTY0LWIyYzUtNGUwNC1iODkwLWQzMjNlYmE3ZDQxOCJdLCJyb2xlcyI6WyJvcmdhbml6YXRpb24uYWRtaW4iLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJjcmVhdGVkQXQiOjE2MDE3Mzc2NzAxMzIsImlhdCI6MTYwMTczNzY3MH0.OGP0GAB29DoEmAMAD4GrZEfjIXmxhpDP8J8LMY6SpiQ'
  apiKeys:
      - ${opt:stage, 'development'}-${self:service}-key

functions:
  resetSession:
    handler: index.handler
    memorySize: 128
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-03f5b485d7cb35d38
      subnetIds:
        - subnet-0a951cac6805bd176
        - subnet-001de5ecd3df6ae3d
    package:
      exclude:
        - '**/**.**'
      include:
        - .build/**
    description: Reset session
    events:
      - http:
          path: /resetSession
          method: POST
          cors: true
