service: resetSession
frameworkVersion: '2'

custom:
  development:
    resetSession: --
  region: us-east-1

  provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  resetSession:
    handler: handler.index
    memorySize: 128
    timeout: 900
    vpc:
      securityGroupIds:
        - 
      subnetIds:
        - 
        - 
    package:
      exclude:
        - '**/**'
      include:
        - ./**
    description: Job verify and update v3Token and refresh_token.
    events:
      - http:
          path: /resetSession
          method: POST
          private: true
