service: resetSession
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: 'us-east-2'

functions:
  resetSession:
    handler: index.handler
    memorySize: 128
    timeout: 30
    vpc:
      securityGroupIds:
        - sg-03f5b485d7cb35d38
      subnetIds:
        - subnet-0a951cac6805bd176
        - subnet-001de5ecd3df6ae3d
    package:
      exclude:
        - '**/**.**'
      include:
        - .build/**
    description: Reset session
    events:
      - http:
          path: /
          method: POST
